version: '3.5'
services:
  app:
    container_name: laravel
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMPOSER_INSTALL: 0
        NPM_INSTALL: 0
    tty: true
    command: ["./docker/project-setup.sh", "php-fpm"]
    environment:
      CONTAINER_NAME: laravel
      DB_HOST: database
      DB_DATABASE: app
      DB_USERNAME: root
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  web:
    image: nginx:alpine
    tty: true
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www

  database:
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
      - ./docker/database:/docker-entrypoint-initdb.d
    tty: true
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "app"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  redis:
    image: redis
    ports:
      - "6382:6379"

volumes:
  database:
    driver: local
